Move app mattermost-app-pagerduty to current repository
mattermost/mattermost-app-pagerduty pull request #2
Opened 2022-12-16 12:42 UTC by liz-segura98

### Summary
- This PR is to upload all the PagerDuty app onto this repository

### Ticket Link
- STILL OPEN [Changes in Subscription methods](https://community.mattermost.com/core/pl/b5xbgy1wwirj5b844skyrtj9qa)
Change permissions and the way a subscription is created

2022-12-20 14:09 UTC, cwarnermm commented
@hanzei - Where do you recommend I focus my review for this PR?

2023-01-03 10:13 UTC, hanzei commented on src/manifest.json
> +    "version": "v1.0.0",
Let's be consistent with the other apps
```suggestion
    "version": "1.0.0",
```

2023-01-05 22:49 UTC, hanzei requested changes
Blocking on https://github.com/mattermost/mattermost-app-pagerduty/issues/4

2023-01-09 16:55 UTC, LizSegura98 commented
Hi @hanzei, the issue with `make dist` is already solved in commit [fe769ae](https://github.com/mattermost/mattermost-app-pagerduty/pull/2/commits/fe769aeeef24810147876fe42b4e207780788774)  and `make dist-dev` on commit [cb4e8fe](https://github.com/mattermost/mattermost-app-pagerduty/pull/2/commits/cb4e8fee4444f0c4e9f8f07e503d93bbbcc151a5)

```
Invoke policy document:
{"Version":"2012-10-17","Statement":[{"Sid":"AllowS3","Effect":"Allow","Action":["s3:GetObject"],"Resource":["arn:aws:s3:::mattermost-aws-apps/manifests/*","arn:aws:s3:::mattermost-aws-apps/static/*"]},{"Sid":"AllowS3list","Effect":"Allow","Action":["s3:ListBucket"],"Resource":["arn:aws:s3:::mattermost-aws-apps"]},{"Sid":"AllowLambda","Effect":"Allow","Action":["lambda:InvokeFunction"],"Resource":["arn:aws:lambda:us-east-1:255909515137:function:trello_0-0-1_trello","arn:aws:lambda:us-east-1:255909515137:function:pagerduty_v1-0-0_pagerduty","arn:aws:lambda:us-east-1:255909515137:function:pagerd_v1-0-0_pagerd","arn:aws:lambda:us-east-1:255909515137:function:opsgenie_1-0-0_bundle","arn:aws:lambda:us-east-1:255909515137:function:pagerduty_1-0-0_bundle"]}]}

You can now install it in Mattermost using:
  /apps install listed pagerduty
```

2023-01-10 16:14 UTC, hanzei approved these changes
AWS deployment works

2023-01-11 00:56 UTC, mickmister requested changes
Great work on this @liz-segura98 :+1: I have a few requests and questions. Comments marked as "Optional" are non-blocking, and are mostly tips to get more use out of the typescript compiler.

2023-01-11 00:56 UTC, mickmister commented on package.json
> +    "node-fetch": "^2.6.7",
`@pagerduty/pdjs` and `node-fetch` are imported by the application so they need to go in `dependencies`

2023-01-11 00:56 UTC, mickmister commented on Dockerfile
> +COPY . .
Optional

Just a comment that doesn't really matter for the purpose of this PR: This should also copy `package-lock.json` before `npm install`

```suggestion
COPY package.json package-lock.json .
RUN npm install
COPY . .
```

2023-01-11 00:56 UTC, mickmister commented on src/api/configure.ts
> +export const configureAdminAccountForm: CallResponseHandler = async (req: Request, res: Response) => {
Optional

Should this `CallResponseHandler` be used on every handler? Also since the function is typed, you don't need to specify the arg types. I just tested this out, and typescript actually doesn't infer the specific request and response based if you specify it this way.

I suggest doing this otherwise the `CallResponseHandler` doesn't help at all:

```suggestion
export const configureAdminAccountForm: CallResponseHandler = async (req, res) => {
```

2023-01-11 00:56 UTC, mickmister commented on src/utils/call-responses.ts
> +) => Promise<void>;
Optional

In reference to me previous comment, you also need to do this to tell typescript what you will receive and what you should respond with:

```suggestion
export type CallResponseHandler = (
    req: Request<unknown, AppCallResponse, AppCallRequest>,
    res: Response<AppCallResponse>
) => Promise<void>;
```

I also had to add this to make eslint approve of this type. This was required with the current version of this type as well.

```json
        "@typescript-eslint/no-unused-vars": ["warn"],
```

2023-01-11 00:56 UTC, mickmister commented on src/api/configure.ts
> +        i18nObj.__('api.configure.follow_account_login', { url: hyperlink('link', <string>connectUrl) });
Optional

I don't understand why we declare this as `string | undefined`, and then assert that it's defined here without first checking if it's defined. It's probably defined, but we should check that if we use `| undefined`. This happens in every API handler.

2023-01-11 00:56 UTC, mickmister commented on src/api/help.ts
> +        commands.push(addBulletSlashCommand(`${Commands.DISCONNECT}`, i18nObj.__('api.help.command_disconnect')));
`connect` should only show for unconnected users, and `disconnect` should only show for connected users

2023-01-11 00:56 UTC, mickmister commented on src/locales/en.json
> +			"subcription": {
```suggestion
			"subscription": {
```

2023-01-11 00:56 UTC, mickmister commented on src/api/incident.ts
> +        callResponse = newErrorCallResponseWithMessage(i18nObj.__('api.incident.created_error', { messaage: error.message }));
@srkgupta What are the principles you want to enforce on errors we return to the user? There was a comment on the Drive PR that said we shouldn't return an error we receive from the Drive API

2023-01-11 00:56 UTC, mickmister commented on src/api/index.ts
> +router.post(`${Routes.App.CallPathConfigSubmit}`, cConfigure.configureAdminAccountSubmit);
Any admin routes should use middleware to defend against non-admins accessing this endpoint

2023-01-11 00:56 UTC, mickmister commented on src/api/webhook.ts
> +        console.log('webhook', webhookRequest.data.event);
```suggestion
```

2023-01-11 00:56 UTC, mickmister commented on src/bindings/slash_commands.ts
> +        bindings.push(accountLogoutBinding(context));
These should also be adjusted to if the user is connected or not

2023-01-11 00:56 UTC, mickmister commented on src/clients/mattermost.ts
> +    public updateRolesByUser(userId: string, roles: string): Promise<any> {
Can we remove this to avoid confusion?

2023-01-11 00:56 UTC, mickmister commented on src/api/install.ts
> +    await mattermostClient.updateRolesByUser(<string>userId, 'system_user system_post_all');
We should not escalate the bot's permissions

2023-01-11 00:56 UTC, mickmister commented on src/constant/forms.ts
> +});
Optional

You can use this to have typescript enforce the readonly aspect of the object:

```suggestion
export const NoteModalForm = Object.freeze({
    NOTE_MESSAGE: 'incident_message',
}) as const;
```

2023-01-11 00:56 UTC, mickmister commented on src/constant/options.ts
> +        value: option_time_5m,
Should these be localized? Same with most strings in this file

2023-01-11 00:56 UTC, mickmister commented on src/types/mattermost.ts
> +export type DialogElementText = {
All of the `Dialog*` types should be removed

2023-01-11 00:56 UTC, mickmister commented on src/locales/en.json
> +		}
How does this work?

2023-01-11 00:56 UTC, mickmister commented on src/locales/en.json
> +			"incident-failed\"": "forms.resolved.incident-failed\""
Why have the extra quotes here?

```suggestion
			"incident-failed": "forms.resolved.incident-failed"
```

2023-01-11 00:56 UTC, mickmister commented on src/locales/en.json
> +			"create-incident-exception": "Required data not sended [Impacted service and title]"
```suggestion
			"add-incident-exception": "Required data not sent [Impacted service and title]",
			"create-incident-exception": "Required data not sent [Impacted service and title]"
```

2023-01-11 00:56 UTC, mickmister commented on src/forms/subscription-add.ts
> +    const channelId: string = values?.[SubscriptionCreateForm.CHANNEL_ID].value;
This should be done on `call.context.channel.id` instead of having this field in the form. This should be applied to all apps

2023-01-11 00:56 UTC, mickmister commented on src/forms/resolve-incident.ts
> +    }
Not sure if optional

Should we instead let this error bubble up to the calling function?

2023-01-11 00:56 UTC, mickmister commented on src/forms/pagerduty-options.ts
> +        const options: AppSelectOption[] = [...users.map((b: any) => {
Optional

```suggestion
        const options: AppSelectOption[] = users.map((b: any) => {
```

2023-01-11 00:56 UTC, mickmister commented on src/forms/pagerduty-options.ts
> +        const options: AppSelectOption[] = [...services.map((b: any) => {
Optional

```suggestion
        const options: AppSelectOption[] = services.map((b: any) => {
```

2023-01-11 00:56 UTC, mickmister commented on src/forms/oauth.ts
> +        user_id: botUserID,
Optional

I don't think we need the `user_id` here

2023-01-11 00:56 UTC, mickmister commented on src/forms/incident-create.ts
> +    if (Boolean(values.incident_assign_to)) {
Optional

These calls to `Boolean` redundant

```suggestion
    if (values.incident_assign_to) {
```

2023-01-11 00:56 UTC, mickmister commented on README.md
> +This application allows you to integrate PagerDuty to your Mattermost instance, letting you subscribe your PagerDuty's services on any custom channel to get notified about any update related to your
```suggestion
This application allows you to integrate PagerDuty to your Mattermost instance, letting you subscribe your PagerDuty's services on any custom channel to be notified about any update related to your services. Also, allows the user to create or display incidents, watch who is on-call, etc. without leaving the Mattermost window.
```

2023-01-11 00:56 UTC, mickmister commented on README.md
> +To install, as a Mattermost system admin user, run the command ``/apps install http PAGERDUTY_API`` in any channel. The ``/pd`` command should be available after the configuration has been successful
```suggestion
To install, as a Mattermost system admin user, run the command ``/apps install http PAGERDUTY_API`` in any channel. The ``/pd`` command should be available after the app has been successfully installed.
```

2023-01-11 00:56 UTC, mickmister commented on README.md
> +The ``PAGERDUTY_API`` should be replaced with the URL where the Trello API instance is running. Example: ``/apps install http https://myapp.com/manifest.json``
```suggestion
The ``PAGERDUTY_API`` should be replaced with the URL where this PagerDuty integration is running. Example: ``/apps install http https://myapp.com/manifest.json``
```

2023-01-11 00:56 UTC, mickmister commented on README.md
> +To install, as a Mattermost system admin user, run the command ``/apps install listed pagerduty`` in any channel. The ``/pd`` command should be available after the configuration has been successfully
Same comment as in other PRs

```suggestion
To install, as a Mattermost system admin user, open the Mattermost Marketplace and select **Install** located next to the PagerDuty app. The ``/pd`` command should be available after the integration has been successfully installed.
```

2023-01-11 00:56 UTC, mickmister commented on README.md
> +1. Open your PagerDuty profile to get your credentials and link to your Mattermost instance.
```suggestion
1. Open your PagerDuty profile to get your credentials, and follow the steps below to link to your Mattermost instance. 
```

2023-01-11 00:56 UTC, mickmister commented on README.md
> +2. Select the **Integration** tab in the toolbar. To the right of the popup (in the **Developer Tools** column) select **Developer Mode**
```suggestion
2. Select the **Integration** tab in the toolbar. To the right of the popup (in the **Developer Tools** column) select **Developer Mode**.
```

2023-01-11 00:56 UTC, mickmister commented on README.md
> +7. The ``Client ID`` and ``Client Secret`` will be displayed. Save them in a safe place - the ``Client Secret`` can't be recovered).
```suggestion
7. The ``Client ID`` and ``Client Secret`` will be displayed. Temporarily copy them in order to use them in a step in the next section - the ``Client Secret`` can't be recovered). 
```

2023-01-11 00:56 UTC, mickmister commented on README.md
> +- ``/pd subscription delete``: Will allow you to remove a subscription. No more notifications from that team will be received.
These descriptions should change after we change the subscription feature to be channel-aware, i.e. using `context.channel.id`

2023-01-23 17:02 UTC, LizSegura98 commented
Hi @srkgupta and @mickmister, in this PR are the changes for the [(Security Issues)](https://github.com/liz-segura98/mattermost-app-pagerduty/pull/1):

This PR will solve all the security issues reported on current open PR and Mattermost Channel:

- Link to Security Issues comment [(security-issues-report)](https://community.mattermost.com/core/pl/sojqu6kie3yexyhimi36ib3pnh)

Changes done in this PR:
- Removed changes of Bot's permission (not more system_admin)
- Validate that only system_admin role users could execute /configure command
- Validate that the user is connected before doing any request to PagerDuty service

2023-02-15 08:11 UTC, srkgupta approved these changes
All the security issues identified have been fixed and is validated. The PR looks good from security perspective.

2023-02-15 12:40 UTC, hanzei commented
@liz-segura98 Is the subscription issue linked in the description fixed yet?

2023-02-16 17:00 UTC, liz-segura98 commented
> @liz-segura98 Is the subscription issue linked in the description fixed yet?

Yes! I forgot to update the comment section.

2023-02-23 17:18 UTC, mickmister approved these changes

2023-02-23 21:18 UTC, merged